name: Upload to S3
on:
  push:
      branches:
        - main
  workflow_dispatch:
    inputs:
      enviroment:
        type: choice
        description: 'upadata enviroment'
        required: true
        default: 'main'
        options:
          - 'ChiYmiya'
          - 'Jingbo'
          - 'docs'
          - 'ldw'
          - 'piprot'
          - 'zhang'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@master  

      - name: Install Dependencies
        run: npm install
        
      - name: List files in the repository
        run: |
          ls -al
          
      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  |
          aws s3 cp --recursive --region ap-southeast-1 dist s3://majiang/mahjong/"${{ github.event.inputs.language }}"/"${{ github.event.inputs.enviroment }}"
          
